# Generated by Django 6.0.6 on 2026-06-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['state'], name='fuel_fuelst_state_641286_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['city'], name='fuel_fuelst_city_f05e48_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['retail_price'], name='fuel_fuelst_retail__3784a3_idx'),
        ),
    ]
